/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    industries: Industry;
    services: Service;
    projects: Project;
    posts: Post;
    pages: Page;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site_settings: SiteSetting;
  };
  globalsSelect: {
    site_settings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'editor') | null;
  /**
   * Short author bio for blog bylines.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility + SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * e.g. 01
   */
  number?: string | null;
  title: string;
  lead: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  stat_value?: string | null;
  stat_label?: string | null;
  hero_image?: (number | null) | Media;
  /**
   * Hero eyebrow, e.g. // For 2–30 person law firms
   */
  eyebrow?: string | null;
  /**
   * Big H1. Wrap the accent in *asterisks*. Falls back to the title.
   */
  hero_heading?: string | null;
  /**
   * Long hero paragraph. Falls back to the card lead.
   */
  hero_lead?: string | null;
  /**
   * Hero stat row (the count-up figures). Hidden if empty.
   */
  hero_metrics?:
    | {
        /**
         * e.g. 9, 0, or 1
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Big statement under the hero. Wrap accent part in *asterisks*. Hidden if empty.
   */
  manifesto?: string | null;
  /**
   * Scrolly case-study section. Hidden if it has no steps.
   */
  story?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    steps?:
      | {
          /**
           * e.g. 01
           */
          num: string;
          cap: string;
          title: string;
          desc: string;
          tags?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Capability "full library" section. Hidden if it has no groups.
   */
  library?: {
    /**
     * e.g. // The full library
     */
    eyebrow?: string | null;
    /**
     * Wrap the accent-coloured part in *asterisks*, e.g. “SEO that drives *revenue,* not just rankings.”
     */
    heading?: string | null;
    lead?: string | null;
    /**
     * Explains each tag colour (Connects / We set up / Your edge).
     */
    legend?:
      | {
          tag: 'core' | 'set' | 'edge';
          /**
           * e.g. "to software you already have"
           */
          label: string;
          id?: string | null;
        }[]
      | null;
    groups?:
      | {
          /**
           * e.g. // 01
           */
          num: string;
          title: string;
          /**
           * Right-aligned caption, e.g. "front of the funnel"
           */
          subtitle?: string | null;
          modules?:
            | {
                title: string;
                tag: 'core' | 'set' | 'edge';
                desc: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * e.g. // 07
     */
    packs_num?: string | null;
    packs_title?: string | null;
    packs_lead?: string | null;
    /**
     * Practice-area chips. Hidden if empty.
     */
    packs?:
      | {
          name: string;
          /**
           * Mono caption, e.g. "IRCC / USCIS"
           */
          sub?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Dashed "keepbar" callout under the library. Hidden if no title.
     */
    callout?: {
      /**
       * Emoji, e.g. 🗂️
       */
      icon?: string | null;
      title?: string | null;
      text?: string | null;
    };
  };
  /**
   * Process timeline. Hidden if empty.
   */
  process?:
    | {
        /**
         * e.g. Week 1 / Ongoing
         */
        step: string;
        title: string;
        desc: string;
        /**
         * Dims the step (upcoming phase).
         */
        future?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        unit?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Heading of the FAQ aside. Wrap accent in *asterisks*. Falls back to "<Title> questions."
   */
  faq_heading?: string | null;
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related industries shown at the foot of the page.
   */
  related?: (number | Industry)[] | null;
  /**
   * Closing CTA band. Falls back to a generic CTA when the heading is blank.
   */
  cta?: {
    /**
     * e.g. // Get started
     */
    eyebrow?: string | null;
    /**
     * Wrap the accent-coloured part in *asterisks*, e.g. “SEO that drives *revenue,* not just rankings.”
     */
    heading?: string | null;
    text?: string | null;
    primary_label?: string | null;
    /**
     * e.g. mailto:hello@structure.studio or /contact
     */
    primary_href?: string | null;
    secondary_label?: string | null;
    secondary_href?: string | null;
  };
  extra_blocks?: (RichTextBlock | StatsBlock | GalleryBlock | MediaTextBlock | CtaBlock)[] | null;
  /**
   * URL segment. Auto-generated from the title if left empty.
   */
  slug?: string | null;
  /**
   * Optional overrides for search/social. Falls back to page title + summary.
   */
  seo?: {
    /**
     * Meta title override (≤ ~60 chars).
     */
    title?: string | null;
    /**
     * Meta description override (≤ ~160 chars).
     */
    description?: string | null;
    /**
     * Open Graph / social share image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Optional // mono label.
   */
  eyebrow?: string | null;
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        value: string;
        /**
         * Small suffix, e.g. %, /100, s.
         */
        unit?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  eyebrow?: string | null;
  items?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock".
 */
export interface MediaTextBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  imageSide?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  eyebrow?: string | null;
  heading: string;
  text?: string | null;
  buttons?:
    | {
        label: string;
        href: string;
        variant?: ('accent' | 'on-dark') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * 01–04
   */
  number?: string | null;
  title: string;
  lead: string;
  /**
   * Shown as chips on the service card.
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Headline figure, e.g. 99.9% or 0.9s.
   */
  metric_value?: string | null;
  /**
   * Caption under the figure.
   */
  metric_label?: string | null;
  hero_image?: (number | null) | Media;
  /**
   * Optional overrides for the single-page hero + section headings. Wrap the accent part in *asterisks*. Each falls back to a sensible default when blank.
   */
  headings?: {
    /**
     * Big H1. Wrap the accent in *asterisks*. Falls back to the service title.
     */
    hero?: string | null;
    /**
     * e.g. // From idea to handoff
     */
    story_eyebrow?: string | null;
    /**
     * Wrap the accent-coloured part in *asterisks*, e.g. “SEO that drives *revenue,* not just rankings.”
     */
    story_heading?: string | null;
    /**
     * Intro under the walkthrough heading.
     */
    story_lead?: string | null;
    /**
     * e.g. // Capabilities
     */
    capabilities_eyebrow?: string | null;
    /**
     * Wrap the accent-coloured part in *asterisks*, e.g. “SEO that drives *revenue,* not just rankings.”
     */
    capabilities_heading?: string | null;
    /**
     * e.g. // Process
     */
    process_eyebrow?: string | null;
    /**
     * Wrap the accent-coloured part in *asterisks*, e.g. “SEO that drives *revenue,* not just rankings.”
     */
    process_heading?: string | null;
    process_lead?: string | null;
    /**
     * e.g. // FAQ
     */
    faq_eyebrow?: string | null;
    /**
     * No accent needed. Falls back to “<Service> questions.”
     */
    faq_heading?: string | null;
  };
  /**
   * Glyph/emoji or icon key.
   */
  icon?: string | null;
  /**
   * Big statement shown under the hero. Hidden if empty.
   */
  manifesto?: string | null;
  /**
   * Stats in the hero. Falls back to the card metric if empty.
   */
  hero_metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Walkthrough steps. Section hidden if empty.
   */
  scrolly?:
    | {
        /**
         * e.g. 01
         */
        num: string;
        /**
         * Short caption.
         */
        cap: string;
        title: string;
        desc: string;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pillar cards (label + description). Section hidden if empty.
   */
  capabilities?:
    | {
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        step: string;
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Result stat strip. Section hidden if empty.
   */
  results?:
    | {
        value: string;
        unit?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Section hidden if empty.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  pricing?: string | null;
  tech?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  extra_blocks?: (RichTextBlock | StatsBlock | GalleryBlock | MediaTextBlock | CtaBlock)[] | null;
  /**
   * URL segment. Auto-generated from the title if left empty.
   */
  slug?: string | null;
  /**
   * Optional overrides for search/social. Falls back to page title + summary.
   */
  seo?: {
    /**
     * Meta title override (≤ ~60 chars).
     */
    title?: string | null;
    /**
     * Meta description override (≤ ~160 chars).
     */
    description?: string | null;
    /**
     * Open Graph / social share image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * e.g. E-commerce · 2026
   */
  meta?: string | null;
  industry?: (number | null) | Industry;
  /**
   * Adds the `feature` class (wide card).
   */
  featured?: boolean | null;
  /**
   * e.g. +212% mobile revenue
   */
  hero_stat?: string | null;
  cover?: (number | null) | Media;
  summary?: string | null;
  client?: string | null;
  duration?: string | null;
  services?: (number | Service)[] | null;
  live_url?: string | null;
  /**
   * Heading for the challenge section.
   */
  challenge_title?: string | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Heading for the approach section.
   */
  approach_title?: string | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stats?:
    | {
        value: string;
        unit?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  related?: (number | Project)[] | null;
  extra_blocks?: (RichTextBlock | StatsBlock | GalleryBlock | MediaTextBlock | CtaBlock)[] | null;
  /**
   * URL segment. Auto-generated from the title if left empty.
   */
  slug?: string | null;
  /**
   * Optional overrides for search/social. Falls back to page title + summary.
   */
  seo?: {
    /**
     * Meta title override (≤ ~60 chars).
     */
    title?: string | null;
    /**
     * Meta description override (≤ ~160 chars).
     */
    description?: string | null;
    /**
     * Open Graph / social share image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  category?: string | null;
  cover?: (number | null) | Media;
  published_at?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  related_posts?: (number | Post)[] | null;
  extra_blocks?: (RichTextBlock | StatsBlock | GalleryBlock | MediaTextBlock | CtaBlock)[] | null;
  /**
   * URL segment. Auto-generated from the title if left empty.
   */
  slug?: string | null;
  /**
   * Optional overrides for search/social. Falls back to page title + summary.
   */
  seo?: {
    /**
     * Meta title override (≤ ~60 chars).
     */
    title?: string | null;
    /**
     * Meta description override (≤ ~160 chars).
     */
    description?: string | null;
    /**
     * Open Graph / social share image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?: (RichTextBlock | StatsBlock | GalleryBlock | MediaTextBlock | CtaBlock)[] | null;
  /**
   * Editable copy for the archive routes (records with slug work / industries / services). Ignored by Core/Legal pages.
   */
  archive?: {
    hero_eyebrow?: string | null;
    hero_heading?: string | null;
    /**
     * Accent-coloured tail of the heading.
     */
    hero_heading_accent?: string | null;
    hero_lead?: string | null;
    hero_stats?:
      | {
          value: string;
          /**
           * Small superscript, e.g. + or /100 or s.
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Industries archive manifesto. Hidden if empty.
     */
    manifesto?: string | null;
    /**
     * Work archive featured case. Falls back to the first featured project.
     */
    featured?: {
      project?: (number | null) | Project;
      eyebrow?: string | null;
      heading?: string | null;
      heading_accent?: string | null;
      desc?: string | null;
      stats?:
        | {
            value: string;
            suffix?: string | null;
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    results_eyebrow?: string | null;
    results_heading?: string | null;
    results_heading_accent?: string | null;
    results_lead?: string | null;
    results_stats?:
      | {
          value: string;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Services archive timeline. Hidden if empty.
     */
    roadmap?:
      | {
          week: string;
          title: string;
          desc: string;
          future?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Services archive pricing models. Hidden if empty.
     */
    engagement?:
      | {
          tag: string;
          title: string;
          price: string;
          price_unit?: string | null;
          desc: string;
          featured?: boolean | null;
          cta_label?: string | null;
          cta_href?: string | null;
          items?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Services archive "we do / we don't" matrix. Hidden if both empty.
     */
    matrix?: {
      do?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
      dont?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * URL segment. Auto-generated from the title if left empty.
   */
  slug?: string | null;
  /**
   * Optional overrides for search/social. Falls back to page title + summary.
   */
  seo?: {
    /**
     * Meta title override (≤ ~60 chars).
     */
    title?: string | null;
    /**
     * Meta description override (≤ ~160 chars).
     */
    description?: string | null;
    /**
     * Open Graph / social share image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  lead?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  stat_value?: T;
  stat_label?: T;
  hero_image?: T;
  eyebrow?: T;
  hero_heading?: T;
  hero_lead?: T;
  hero_metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  manifesto?: T;
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        steps?:
          | T
          | {
              num?: T;
              cap?: T;
              title?: T;
              desc?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  library?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        legend?:
          | T
          | {
              tag?: T;
              label?: T;
              id?: T;
            };
        groups?:
          | T
          | {
              num?: T;
              title?: T;
              subtitle?: T;
              modules?:
                | T
                | {
                    title?: T;
                    tag?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
            };
        packs_num?: T;
        packs_title?: T;
        packs_lead?: T;
        packs?:
          | T
          | {
              name?: T;
              sub?: T;
              id?: T;
            };
        callout?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
            };
      };
  process?:
    | T
    | {
        step?: T;
        title?: T;
        desc?: T;
        future?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        unit?: T;
        label?: T;
        id?: T;
      };
  faq_heading?: T;
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  related?: T;
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        primary_label?: T;
        primary_href?: T;
        secondary_label?: T;
        secondary_href?: T;
      };
  extra_blocks?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        ctaBand?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        unit?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  items?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock_select".
 */
export interface MediaTextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  imageSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  text?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  lead?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  metric_value?: T;
  metric_label?: T;
  hero_image?: T;
  headings?:
    | T
    | {
        hero?: T;
        story_eyebrow?: T;
        story_heading?: T;
        story_lead?: T;
        capabilities_eyebrow?: T;
        capabilities_heading?: T;
        process_eyebrow?: T;
        process_heading?: T;
        process_lead?: T;
        faq_eyebrow?: T;
        faq_heading?: T;
      };
  icon?: T;
  manifesto?: T;
  hero_metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  scrolly?:
    | T
    | {
        num?: T;
        cap?: T;
        title?: T;
        desc?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        label?: T;
        desc?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  results?:
    | T
    | {
        value?: T;
        unit?: T;
        label?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  pricing?: T;
  tech?:
    | T
    | {
        label?: T;
        id?: T;
      };
  extra_blocks?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        ctaBand?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  meta?: T;
  industry?: T;
  featured?: T;
  hero_stat?: T;
  cover?: T;
  summary?: T;
  client?: T;
  duration?: T;
  services?: T;
  live_url?: T;
  challenge_title?: T;
  challenge?: T;
  approach_title?: T;
  approach?: T;
  stats?:
    | T
    | {
        value?: T;
        unit?: T;
        label?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  related?: T;
  extra_blocks?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        ctaBand?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  category?: T;
  cover?: T;
  published_at?: T;
  body?: T;
  author?: T;
  related_posts?: T;
  extra_blocks?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        ctaBand?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        ctaBand?: T | CtaBlockSelect<T>;
      };
  archive?:
    | T
    | {
        hero_eyebrow?: T;
        hero_heading?: T;
        hero_heading_accent?: T;
        hero_lead?: T;
        hero_stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        manifesto?: T;
        featured?:
          | T
          | {
              project?: T;
              eyebrow?: T;
              heading?: T;
              heading_accent?: T;
              desc?: T;
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
            };
        results_eyebrow?: T;
        results_heading?: T;
        results_heading_accent?: T;
        results_lead?: T;
        results_stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        roadmap?:
          | T
          | {
              week?: T;
              title?: T;
              desc?: T;
              future?: T;
              id?: T;
            };
        engagement?:
          | T
          | {
              tag?: T;
              title?: T;
              price?: T;
              price_unit?: T;
              desc?: T;
              featured?: T;
              cta_label?: T;
              cta_href?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
        matrix?:
          | T
          | {
              do?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              dont?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings".
 */
export interface SiteSetting {
  id: number;
  logo?: (number | null) | Media;
  brandWord?: string | null;
  /**
   * Primary top-nav links.
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copy for the Services mega panel. The four service cards are pulled live from the Services collection.
   */
  mega?: {
    eyebrow?: string | null;
    heading?: string | null;
    blurb?: string | null;
    ctaLabel?: string | null;
    /**
     * Featured promo card in the mega panel. Hidden if Title is empty.
     */
    promo?: {
      eyebrow?: string | null;
      title?: string | null;
      linkLabel?: string | null;
      linkHref?: string | null;
    };
  };
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerTagline?: string | null;
  /**
   * Bottom bar of the footer.
   */
  footerBottom?: {
    left?: string | null;
    right?: string | null;
  };
  social?:
    | {
        platform: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Contact-page channels ("Other channels" block).
   */
  contact?: {
    /**
     * Used for the mailto: link.
     */
    email?: string | null;
    /**
     * Email / Telegram / LinkedIn etc. Icons are assigned by position.
     */
    channels?:
      | {
          /**
           * e.g. Email, Telegram, LinkedIn
           */
          platform: string;
          /**
           * Displayed value, e.g. @structurestudio
           */
          handle: string;
          /**
           * Full URL or mailto:
           */
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  brandWord?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  mega?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        blurb?: T;
        ctaLabel?: T;
        promo?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              linkLabel?: T;
              linkHref?: T;
            };
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerTagline?: T;
  footerBottom?:
    | T
    | {
        left?: T;
        right?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        channels?:
          | T
          | {
              platform?: T;
              handle?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}